### ISSUE TITLE
Support for caching

### ISSUE THREAD

**Issue by fkromer** [yezz123/setup-uv#25]
Would be great if caching would be supported out of the box. [setup-cached-uv](https://github.com/hynek/setup-cached-uv) or [setup-python-uv-action](https://github.com/drivendataorg/setup-python-uv-action) could be some inspiration.

**Comment by yezz123** [comment]
Hey @fkromer, supporting caching has been on my mind since the day I released this. I will try to get some inspiration from the tools you share and give it a try.

Thanks for showing interest in this repository!
